### ISSUE TITLE
Bun now supports formData

### ISSUE THREAD

**Issue by emastho** [gornostay25/svelte-adapter-bun#14]
https://github.com/oven-sh/bun/pull/2051

**Comment by bitdom8** [comment]
Hi @emastho , how do you solve this?

Still when using bun server, get problem `Cross-site POST form submissions are forbidden` as the same error on adeptor-auto from sveltekit

**Comment by maietta** [comment]
> Hi @emastho , how do you solve this?
> 
> Still when using bun server, get problem `Cross-site POST form submissions are forbidden` as the same error on adeptor-auto from sveltekit

I just saw your post in my feed and figured I'd throw this out there:

In my NodeJS apps I must specify a ORIGIN environment variable so that I can avoid the CORS issue with my forms in Svelte/React/Angular, etc. The reason is that in my case, I am using CapRover or similar systems for deployments, where my NodeJS apps are running inside LXC or Docker containers and a reverse-proxying webserver will persist in front of my apps.

While I don't know how you're actually deploying or running your apps, what I can say is that it took a while to figure out what my problem. Nobody seemed to have the answer everywhere I looked or asked.

**Comment by bitdom8** [comment]
@maietta thanks. My issue is the same as when node-adaptor is not activated https://kit.svelte.dev/docs/adapter-node. Docu says. But will try your statements.

If adapter-node can't correctly determine the URL of your deployment, you may experience this error when using [form actions](https://kit.svelte.dev/docs/form-actions):

`Cross-site POST form submissions are forbidden`

**Comment by bitdom8** [comment]
managed to have it worked after setting env variables, custom settings and run it `bun run start` on build folder

**Comment by bitdom8** [comment]
Can't get formdata's info

The code below returns:

```
await db.use({ ns: 'xx', db: 'xx' });
      const formData = await request.formData()

      var form = document.getElementById('formForEnhance');
      var formData2 = new FormData(form);
      console.log(formData2, "bu")
    
      const s = formData?.get('code')
      console.log("s, formData, formData.keys", s, formData, formData?.keys(), formData?.values(), formData, "xENDx")
      res = await db.query(`SELECT * FROM bitfiniconauth WHERE code = ${s}`);
```

```
<div class="popup-content">
		<!-- Login form -->
		<!-- variables newwww -->
		<!-- action="https://bitfinicon.com/en?/login" -->
		<!-- action="?/login" -->
		{#if $page.data.user?.name}
		{JSON.stringify($page.data.user.name)}
		{/if}
		<!-- {$page.route.id} -->
		<form
		id="formForEnhance"
			method="POST"
			action="https://bitfinicon.com/en?/login"
			use:enhance={({ form }) => {
				console.log("enHANCE", form, "XXenHANCEXX")
				// Before form submission to server
				return async ({ result, update }) => {
					// After form submission to server
					// console.log("dkf", result.data?.id)
					if (result.type === 'success') {
						// form.reset();
						console.log("Congrats", result)
            if (result.data?.results == code) {
              console.log("Valid", result, JSON.stringify($page.data.user))
			  $login = 'false'
			  
            }
			invalidateAll();
						// remove(result.data?.id)
					}
					// if (result.type === 'invalid') {
					// 	await applyAction(result);
					// }
					// update();
				};
			}}
		>
			<h2>{ip("Login", t)}</h2>
      <p>{ip("Please write Code 123 to our telegram bot, enter the code", t)}</p> 
      <a href="https://t.me/bitfinicon_bot" target="_blank">{ip("Open Telegram BOT", t)}</a>
      <label for="code">{ip("Enter the Code", t)}:</label>
			<input type="text" id="code" name="code" required bind:value={code} /><br />
			<button type="submit">{ip("Login", t)}</button>
		</form>
		<button on:click={() => ($login = 'false')}>{ip("Close", t)}</button>
	</div>
</div>
```


This is returned:
```
s, formData, formData.keys null FormData {
  [Symbol(#d)]: [],
  append: [Function: append],
  delete: [Function: delete],
  get: [Function: get],
  getAll: [Function: getAll],
  has: [Function: has],
  forEach: [Function: forEach],
  set: [Function: set],
  entries: [Function: GeneratorFunction],
  keys: [Function: GeneratorFunction],
  values: [Function: GeneratorFunction],
  [Symbol(Symbol.iterator)]: [Function]
} {} {} FormData {
  [Symbol(#d)]: [],
  append: [Function: append],
  delete: [Function: delete],
  get: [Function: get],
  getAll: [Function: getAll],
  has: [Function: has],
  forEach: [Function: forEach],
  set: [Function: set],
  entries: [Function: GeneratorFunction],
  keys: [Function: GeneratorFunction],
  values: [Function: GeneratorFunction],
  [Symbol(Symbol.iterator)]: [Function]
} xENDx
TypeError: undefined is not an object
{
  name: undefined,
  id: undefined
}`
```

**Comment by bitdom8** [comment]
Hi @gornostay25 any explanation before closing

**Comment by gornostay25** [comment]
@bitdom8 Hi, this issue about FormData support, so i remove pollyfils in new commit so i close issue.
About you're problem, i think you forgot to set ORIGIN in .env file. But you can find this error message in compiled code and debug it

**Comment by bitdom8** [comment]
Thanks @gornostay25 , added already origin. It was working fine. Maybe I changed my structure of URL and addded api. That's why can't overcome this:

![image](https://github.com/gornostay25/svelte-adapter-bun/assets/44948674/07846bd2-5f3e-4fb6-b762-6a13235e0403)

**Comment by bitdom8** [comment]
> Thanks @gornostay25 , added already origin. It was working fine. Maybe I changed my structure of URL and addded api. That's why can't overcome this:
> 
> ![image](https://user-images.githubusercontent.com/44948674/250876427-07846bd2-5f3e-4fb6-b762-6a13235e0403.png)

Also can't really send formdata as stated above, even though now I can send data since it's fixed using bun, data is empty.

Do you have a snippet that works with formdata

**Comment by bitdom8** [comment]
Got error: `FormData parse error missing final boundary`

```
login: async ({ cookies, request, locals }) => {   
49 |     let res;
50 |     try {
51 |       await db.use({ ns: "xx", db: "xx" });
52 |       const formData = await request.formData();     
                                 ^
TypeError: FormData parse error missing final boundary    
      at /usr/local/lsws/nodes/xx/build/server/entries/pages/_lang_/_page.server.ts.js:52:29
```
