### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'server.options.hooks')

### ISSUE THREAD

**Issue by bmccorm2** [gornostay25/svelte-adapter-bun#18]
I know this issue was closed (https://github.com/gornostay25/svelte-adapter-bun/issues/11), but i am getting the exact issue.  . I am doing `bun create svelte-kit bun`, it runs the `vite build` script for me. Then: 

```
bryan@Cave ~/s/bun (main)> bun ./build/index.js 
Listening on 0.0.0.0:3000
708 | 
709 | function defaultAcceptWebsocket(request, upgrade) {
710 |   return upgrade(request);
711 | }
712 | 
713 | if(server.options.hooks.handleWebsocket) {
      ^
TypeError: undefined is not an object (evaluating 'server.options.hooks')
      at /Users/bryan/src/bun/build/index.js:713:3
```

**Comment by kolchurinvv** [comment]
@bmccorm2 are you sure this still applies? I've seen this issue before in the other svelte kit bun adapter.

**Comment by gornostay25** [comment]
I think you are using an old version of the adapter. This code has been changed in newer versions

**Comment by bmccorm2** [comment]
I know a lot has been changing.  I just tried this again per instructions on your blog (https://bun.sh/blog/bun-v0.8.0) and it worked perfectly fine this time!  Thanks for the follow up.
