### ISSUE TITLE
Cannot build with `bun --bun vite build`

### ISSUE THREAD

**Issue by hanssonduck** [gornostay25/svelte-adapter-bun#19]
Bun now supports running vite natively see https://bun.sh/guides/ecosystem/vite.
However I'm not able to build the app inside Bun, the modules are transformed but nothing is emitted.
Here is a reproduction https://github.com/hanssonduck/svelte-bun-build. Clone it and try to run `build` (using `bun upgrade --canary` or `v0.7.2` when it's out).

**Comment by pooledge** [comment]
This should be working now with `v0.7.3`.

I cannot seem to get it running @ localhost via e.g. `HOST=http://localhost bun ./build/index.js` though:
```bash
$ bun ./build/index.js
[0.04ms] ".env"
Listening on http://localhost:3000
685 |     return console.error(error), new Response("Uh oh!!", { status: 500 });
686 |   }
687 | };
688 | websocket && (serverOptions.websocket = websocket);
689 | console.info(`Listening on ${hostname + ":" + port}` + (websocket ? " (Websocket)" : ""));
690 | serve2(serverOptions);
   ^
error: Failed to start server. Is port 3000 in use?
```

I'm pretty sure it's *not* in use, as omitting the `env` setting i.e. defaulting host to `0.0.0.0` works fine

**Comment by pooledge** [comment]
> I cannot seem to get it running @ localhost via e.g. HOST=http://localhost bun ./build/index.js though

Okay I'm an idiot, `HOST=localhost bun ./build/index.js` works fine.

@hanssonduck can you try upgrading?

**Comment by hanssonduck** [comment]
> OST=localhost bun ./build/index.js

Yeah everything works now 🚀
