### ISSUE TITLE
SSG support

### ISSUE THREAD

**Issue by WarningImHack3r** [gornostay25/svelte-adapter-bun#26]
Is there a way to create a static bundle with Bun and SvelteKit? I want to generate a static site for GitHub Pages, but AFAIK it's not possible atm.

Will there be an option to generate a static output instead of creating a Bun server? Or does Bun work with `@sveltejs/adapter-static`?

**Comment by notramo** [comment]
@WarningImHack3r, the static adapter works with Bun. The point of this project is to use the built-in Bun HTTP server instead of the Node-compatible one when running in Bun. Static site generation does not use these, so the proper way of doing static sites is the static adapter.

**Comment by WarningImHack3r** [comment]
Ok thanks good to know!
