### ISSUE TITLE
Websocket unable to be upgraded on connection "keep-alive"

### ISSUE THREAD

**Issue by SabertoothDiego** [gornostay25/svelte-adapter-bun#27]
I wanted to write a small websocket test application with bun and svelte.
When the page was loading I always got an error that firefox could not establish a connection.

After a bit of digging I logged my request:
```
Request (0 KB) {
  method: "GET",
  url: "http://localhost:3000/ws",
  headers: Headers {
    "host": "localhost:3000",
    "user-agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0",
    ...
    "connection": "keep-alive, Upgrade",
    "pragma": "no-cache",
    "cache-control": "no-cache",
    "upgrade": "websocket"
  }
}
```

Firefox sent the "keep-alive" parameter alongside the "Upgrade" parameter for the connection.
This didn't match the condition in the **httpserver** for `req.headers.get("connection")?.toLowerCase() === "upgrade"` and thus never called `upgrade`.

Could the condition perhaps be changed to have the "connection" header checked to include "upgrade" as a value?
An alternative to that could also be splitting the header for possible parts and check the resulting array for the value.

**Comment by btyler** [comment]
This works: req.headers.get("connection")?.toLowerCase().includes("upgrade")
