### ISSUE TITLE
Body is empty when using +server.ts

### ISSUE THREAD

**Issue by alex-pirogov** [gornostay25/svelte-adapter-bun#43]
Hey!

I have the following handler in my project:
```
import { json, type RequestHandler } from '@sveltejs/kit'

export const POST: RequestHandler = async ({ request }) => {
	return json({ data: await request.json() })
}
```
The app is served with docker and proxied with nginx. When testing this endpoint with curl i receive following response, which means i cant read the body of my request.
```
curl  -X POST \
  'https://lk.qastud.io/tasks/field_validation' \
  --header 'Content-Type: application/json' \
  --data-raw '{"hello": "world"}'
{"data":""}
```
I've confirmed the body is transferred correctly to my server by adding body's content to nginx response headers.
And also i've tried to deploy my app using node adapter and it works perfectly fine.

**Comment by ambergristle** [comment]
i ran into the same issue, running `bun:1.0-slim`. swapping
- i'm using superforms, but it doesn't seem like that plays a role
- here's the repo, which i've deployed using a dockerfile: https://github.com/ambergristle/fly-lo
- below are the package versions that seemed most relevant
```
"@sveltejs/kit": "^2.0.0",
"svelte-adapter-bun": "^0.5.1",
"vite": "^5.0.3"
```

@gornostay25 i'm down to help investigate this, and to contribute to the `svelte-adapter-bun` project more generally

**Comment by zakius** [comment]
for me it seems POST breaks when using hooks to modify locals, can't access body or form data, it just hangs there
using the node adapter works fine

**Comment by KaKi87** [comment]
Hello,

> POST breaks [...] can't access body or form data, it just hangs there

I'm experiencing the same issue, even without hooks.

Any news on this @gornostay25 ?

Thanks
