### ISSUE TITLE
[Bug] Await not working during SSR

### ISSUE THREAD

**Issue by KaKi87** [gornostay25/svelte-adapter-bun#45]
Hi,

When using `{#await data.foo}` in template, the content between *before* `{:then foo}` is displayed before SSR, instead of the content *after* it.

Thanks

**Comment by KaKi87** [comment]
During CSR yes, but during SSR, the server is supposed to wait for the `Promise` before rendering.

**Comment by KyleFontenot** [comment]
What version of Kit are you on? I'd think you'd be awaiting the promise server-side then. 
Are you going along the lines of this?: https://kit.svelte.dev/docs/load#streaming-with-promises

They changed the default behavior of this in newer version. so I'm thinking you may be on the newer version that does not await the first returned value in page load.?

**Comment by KaKi87** [comment]
Indeed I am. So you're not going to follow this change ?

**Comment by KyleFontenot** [comment]
> Indeed I am. So you're not going to follow this change ?

I'm not a maintainer, I'm just trying to help. 👍  I wouldn't think that it is the adapter that'd be ignoring an implicit `await`, but I don't know the guts enough. Best of luck

**Comment by KaKi87** [comment]
Sorry for the confusion :sweat_smile: And thanks for trying :pray:
