### ISSUE TITLE
Error: writeCache has been removed

### ISSUE THREAD

**Issue by TheOtterlord** [gornostay25/svelte-adapter-bun#5]
Setting up the Sveltekit skeleton project, replacing the adapter with svelte-adapter-bun causes this error upon building.

```
$ vite build
vite v3.0.2 building for production...
✓ 13 modules transformed.
.svelte-kit/output/client/manifest.json                                   1.22 KiB
.svelte-kit/output/client/_app/immutable/layout.svelte-975ed711.js        0.53 KiB / gzip: 0.35 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-c03d7040.js         1.56 KiB / gzip: 0.75 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-c148cfc2.js   0.80 KiB / gzip: 0.47 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-03969575.js         6.85 KiB / gzip: 2.80 KiB
.svelte-kit/output/client/_app/immutable/start-043b647a.js                23.87 KiB / gzip: 8.98 KiB
vite v3.0.2 building SSR bundle for production...
✓ 11 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/manifest.json                             1.12 KiB
.svelte-kit/output/server/index.js                                  76.10 KiB
.svelte-kit/output/server/entries/fallbacks/layout.svelte.js        0.25 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js         0.74 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js             0.34 KiB
.svelte-kit/output/server/_app/immutable/chunks/index-3e01a4ca.js   2.61 KiB
.svelte-kit/output/server/_app/immutable/chunks/hooks-bced8853.js   0.00 KiB

Run npm run preview to preview your production build locally.
(node:14812) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

> Using svelte-adapter-bun
error during build:
Error: writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-bun
    at Object.writeStatic (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/@sveltejs/kit/dist/chunks/index2.js:185:10)
    at adapt (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/svelte-adapter-bun/index.js:23:12)
    at adapt (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/@sveltejs/kit/dist/chunks/index2.js:212:8)
    at Object.closeBundle (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/@sveltejs/kit/dist/vite.js:3203:11)
    at async Promise.all (index 0)
    at async Object.close (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/rollup/dist/es/shared/rollup.js:23661:13)
    at async Promise.all (index 0)
    at async build (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/vite/dist/node/chunks/dep-1513d487.js:43302:13)
    at async CAC.<anonymous> (file:///home/otterlord/Documents/Repos/sveltekit-bun-template/node_modules/vite/dist/node/cli.js:747:9)
Script error "build" exited with 1 status
```

**Comment by M6268** [comment]
Same issue

`$ vite build
▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    jsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

vite v3.0.2 building for production...
✓ 34 modules transformed.
.svelte-kit/output/client/_app/immutable/assets/svelte-logo-87df40b8.svg                           1.85 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2   15.40 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2      7.33 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2          10.27 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2       8.89 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2          15.90 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2      11.10 KiB
.svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff             75.55 KiB
.svelte-kit/output/client/manifest.json                                                            5.34 KiB
.svelte-kit/output/client/_app/immutable/pages/__layout.svelte-1f3f37b0.js                         4.77 KiB / gzip: 1.86 KiB
.svelte-kit/output/client/_app/immutable/error.svelte-3b008104.js                                  1.56 KiB / gzip: 0.74 KiB
.svelte-kit/output/client/_app/immutable/pages/about.svelte-f2eb44bc.js                            2.51 KiB / gzip: 1.15 KiB
.svelte-kit/output/client/_app/immutable/pages/index.svelte-c68bb3e7.js                            5.47 KiB / gzip: 2.42 KiB
.svelte-kit/output/client/_app/immutable/pages/todos/index.svelte-b1b369bb.js                      6.86 KiB / gzip: 2.88 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-4fdc4e88.js                                  0.43 KiB / gzip: 0.30 KiB
.svelte-kit/output/client/_app/immutable/chunks/singletons-eca981c1.js                             0.05 KiB / gzip: 0.07 KiB
.svelte-kit/output/client/_app/immutable/start-dc7f8f59.js                                         23.80 KiB / gzip: 8.85 KiB
.svelte-kit/output/client/_app/immutable/chunks/index-b1fe9a41.js                                  11.80 KiB / gzip: 5.02 KiB
.svelte-kit/output/client/_app/immutable/assets/about-9682aba9.css                                 0.11 KiB / gzip: 0.10 KiB
.svelte-kit/output/client/_app/immutable/assets/index-5c3529b5.css                                 3.70 KiB / gzip: 1.03 KiB
.svelte-kit/output/client/_app/immutable/assets/index-8bad58d3.css                                 1.45 KiB / gzip: 0.52 KiB
.svelte-kit/output/client/_app/immutable/assets/__layout-f74aac7c.css                              5.08 KiB / gzip: 1.56 KiB
vite v3.0.2 building SSR bundle for production...
✓ 35 modules transformed.
.svelte-kit/output/server/manifest.json                             2.44 KiB
.svelte-kit/output/server/index.js                                  76.18 KiB
.svelte-kit/output/server/entries/endpoints/todos/index.js          1.35 KiB
.svelte-kit/output/server/entries/pages/__layout.svelte.js          4.64 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js         0.74 KiB
.svelte-kit/output/server/entries/pages/about.svelte.js             1.40 KiB
.svelte-kit/output/server/entries/pages/index.svelte.js             8.24 KiB
.svelte-kit/output/server/entries/pages/todos/index.svelte.js       5.95 KiB
.svelte-kit/output/server/_app/immutable/chunks/index-5d84e3f4.js   4.15 KiB
.svelte-kit/output/server/_app/immutable/chunks/hooks-2eea69e9.js   0.46 KiB
(node:164207) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Run npm run preview to preview your production build locally.

> Using svelte-adapter-bun
error during build:
Error: writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-bun
    at Object.writeStatic (file:///home/manuks/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:185:10)
    at adapt (file:///home/manuks/my-app/node_modules/svelte-adapter-bun/index.js:23:12)
    at adapt (file:///home/manuks/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:212:8)
    at Object.closeBundle (file:///home/manuks/my-app/node_modules/@sveltejs/kit/dist/vite.js:3140:11)
    at async Promise.all (index 0)
    at async Object.close (file:///home/manuks/my-app/node_modules/rollup/dist/es/shared/rollup.js:23661:13)
    at async Promise.all (index 0)
    at async build (file:///home/manuks/my-app/node_modules/vite/dist/node/chunks/dep-1513d487.js:43302:13)
    at async CAC.<anonymous> (file:///home/manuks/my-app/node_modules/vite/dist/node/cli.js:747:9)
Script error "build" exited with 1 status`


package.json

`{
  "name": "my-app",
  "version": "0.0.1",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "package": "svelte-kit package",
    "preview": "vite preview",
    "prepare": "svelte-kit sync",
    "check": "svelte-check --tsconfig ./jsconfig.json",
    "check:watch": "svelte-check --tsconfig ./jsconfig.json --watch",
    "lint": "prettier --check --plugin-search-dir=. .",
    "format": "prettier --write --plugin-search-dir=. ."
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "next",
    "@sveltejs/kit": "next",
    "@types/cookie": "^0.5.1",
    "prettier": "^2.6.2",
    "prettier-plugin-svelte": "^2.7.0",
    "svelte": "^3.46.0",
    "svelte-adapter-bun": "^0.3.0",
    "svelte-check": "^2.7.1",
    "sveltekit-adapter-html-like": "^0.2.1",
    "typescript": "^4.7.4",
    "vite": "^3.0.0"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.5.0",
    "@sveltejs/adapter-node": "^1.0.0-next.82",
    "cookie": "^0.4.1",
    "json5": "^2.2.1"
  }
}`

**Comment by gornostay25** [comment]
> Same issue
> 
> `$ vite build ▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]
> 
> ```
> jsconfig.json:2:12:
>   2 │   "extends": "./.svelte-kit/tsconfig.json",
>     ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```
> 
> vite v3.0.2 building for production... ✓ 34 modules transformed. .svelte-kit/output/client/_app/immutable/assets/svelte-logo-87df40b8.svg 1.85 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-ext-400-normal-3df7909e.woff2 15.40 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-ext-400-normal-9e2fe623.woff2 7.33 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-greek-400-normal-a8be01ce.woff2 10.27 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-cyrillic-400-normal-c7d433fd.woff2 8.89 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-400-normal-e43b3538.woff2 15.90 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-latin-ext-400-normal-6bfabd30.woff2 11.10 KiB .svelte-kit/output/client/_app/immutable/assets/fira-mono-all-400-normal-1e3b098c.woff 75.55 KiB .svelte-kit/output/client/manifest.json 5.34 KiB .svelte-kit/output/client/_app/immutable/pages/__layout.svelte-1f3f37b0.js 4.77 KiB / gzip: 1.86 KiB .svelte-kit/output/client/_app/immutable/error.svelte-3b008104.js 1.56 KiB / gzip: 0.74 KiB .svelte-kit/output/client/_app/immutable/pages/about.svelte-f2eb44bc.js 2.51 KiB / gzip: 1.15 KiB .svelte-kit/output/client/_app/immutable/pages/index.svelte-c68bb3e7.js 5.47 KiB / gzip: 2.42 KiB .svelte-kit/output/client/_app/immutable/pages/todos/index.svelte-b1b369bb.js 6.86 KiB / gzip: 2.88 KiB .svelte-kit/output/client/_app/immutable/chunks/index-4fdc4e88.js 0.43 KiB / gzip: 0.30 KiB .svelte-kit/output/client/_app/immutable/chunks/singletons-eca981c1.js 0.05 KiB / gzip: 0.07 KiB .svelte-kit/output/client/_app/immutable/start-dc7f8f59.js 23.80 KiB / gzip: 8.85 KiB .svelte-kit/output/client/_app/immutable/chunks/index-b1fe9a41.js 11.80 KiB / gzip: 5.02 KiB .svelte-kit/output/client/_app/immutable/assets/about-9682aba9.css 0.11 KiB / gzip: 0.10 KiB .svelte-kit/output/client/_app/immutable/assets/index-5c3529b5.css 3.70 KiB / gzip: 1.03 KiB .svelte-kit/output/client/_app/immutable/assets/index-8bad58d3.css 1.45 KiB / gzip: 0.52 KiB .svelte-kit/output/client/_app/immutable/assets/__layout-f74aac7c.css 5.08 KiB / gzip: 1.56 KiB vite v3.0.2 building SSR bundle for production... ✓ 35 modules transformed. .svelte-kit/output/server/manifest.json 2.44 KiB .svelte-kit/output/server/index.js 76.18 KiB .svelte-kit/output/server/entries/endpoints/todos/index.js 1.35 KiB .svelte-kit/output/server/entries/pages/__layout.svelte.js 4.64 KiB .svelte-kit/output/server/entries/fallbacks/error.svelte.js 0.74 KiB .svelte-kit/output/server/entries/pages/about.svelte.js 1.40 KiB .svelte-kit/output/server/entries/pages/index.svelte.js 8.24 KiB .svelte-kit/output/server/entries/pages/todos/index.svelte.js 5.95 KiB .svelte-kit/output/server/_app/immutable/chunks/index-5d84e3f4.js 4.15 KiB .svelte-kit/output/server/_app/immutable/chunks/hooks-2eea69e9.js 0.46 KiB (node:164207) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time (Use `node --trace-warnings ...` to show where the warning was created)
> 
> Run npm run preview to preview your production build locally.
> 
> > Using svelte-adapter-bun
> > error during build:
> > Error: writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-bun
> > at Object.writeStatic (file:///home/manuks/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:185:10)
> > at adapt (file:///home/manuks/my-app/node_modules/svelte-adapter-bun/index.js:23:12)
> > at adapt (file:///home/manuks/my-app/node_modules/@sveltejs/kit/dist/chunks/index2.js:212:8)
> > at Object.closeBundle (file:///home/manuks/my-app/node_modules/@sveltejs/kit/dist/vite.js:3140:11)
> > at async Promise.all (index 0)
> > at async Object.close (file:///home/manuks/my-app/node_modules/rollup/dist/es/shared/rollup.js:23661:13)
> > at async Promise.all (index 0)
> > at async build (file:///home/manuks/my-app/node_modules/vite/dist/node/chunks/dep-1513d487.js:43302:13)
> > at async CAC. (file:///home/manuks/my-app/node_modules/vite/dist/node/cli.js:747:9)
> > Script error "build" exited with 1 status`
> 
> package.json
> 
> `{ "name": "my-app", "version": "0.0.1", "scripts": { "dev": "vite dev", "build": "vite build", "package": "svelte-kit package", "preview": "vite preview", "prepare": "svelte-kit sync", "check": "svelte-check --tsconfig ./jsconfig.json", "check:watch": "svelte-check --tsconfig ./jsconfig.json --watch", "lint": "prettier --check --plugin-search-dir=. .", "format": "prettier --write --plugin-search-dir=. ." }, "devDependencies": { "@sveltejs/adapter-auto": "next", "@sveltejs/kit": "next", "@types/cookie": "^0.5.1", "prettier": "^2.6.2", "prettier-plugin-svelte": "^2.7.0", "svelte": "^3.46.0", "svelte-adapter-bun": "^0.3.0", "svelte-check": "^2.7.1", "sveltekit-adapter-html-like": "^0.2.1", "typescript": "^4.7.4", "vite": "^3.0.0" }, "type": "module", "dependencies": { "@fontsource/fira-mono": "^4.5.0", "@sveltejs/adapter-node": "^1.0.0-next.82", "cookie": "^0.4.1", "json5": "^2.2.1" } }`

Just run `npm run prepare` to create .svelte-kit

**Comment by gornostay25** [comment]
https://github.com/gornostay25/svelte-adapter-bun/commit/a07ddb5e534f41ea5dcf5b8873a26733d176f8a6
