### ISSUE TITLE
Does not support BODY_SIZE_LIMIT

### ISSUE THREAD

**Issue by deme3** [gornostay25/svelte-adapter-bun#56]
Came across this while developing on Bun, however, my web app needs to let users upload large files. Currently, this adapter will drop requests with a large body, although there doesn't seem to be any explicit check in the source code.

Could this be a limitation of whatever this adapter is using to prepare request handling? Note that there is no error server-side, the connection is just closed by the server (`NS_ERROR_NET_RESET`).

In the `@sveltejs/adapter-node`, the following lines handle the body:

https://github.com/sveltejs/kit/blob/c175335f48639eaad8274cb628c6f6549ea4ef7b/packages/kit/src/exports/node/index.js#L6C1-L96C2

Any ideas?

**Comment by ivarlovlie** [comment]
[Bun has a default maxRequestBodySize of 128MB](https://github.com/oven-sh/bun/blob/84d81c3002bf68f913712b492a7aff988ad4c151/packages/bun-types/bun.d.ts#L2193), currently looks like this is not an editable setting from the adapter. Should be a pretty fast implement though.

**Comment by deme3** [comment]
> [Bun.serve has a default maxRequestBodySize of 128MB](https://github.com/oven-sh/bun/blob/84d81c3002bf68f913712b492a7aff988ad4c151/packages/bun-types/bun.d.ts#L2193), currently looks like this is not an editable setting from the adapter. Should be a pretty fast implement though.

Thanks for the input. I didn't notice that at first. It is indeed a fast implement.
