### ISSUE TITLE
v0.3.2 does not published to npm

### ISSUE THREAD

**Issue by rayriffy** [gornostay25/svelte-adapter-bun#9]
latest version of `svelte-adapter-bun` in [npm] is **0.3.1**, current SvelteKit somewhat unusable without patches from https://github.com/gornostay25/svelte-adapter-bun/issues/7 which you already defined to be released in 0.3.2. Maybe you forget to publish package after [commit bump](https://github.com/gornostay25/svelte-adapter-bun/commit/674ed2b9d2fbbbdcdef8349d863dc1cd46b41289)?

**Comment by rayriffy** [comment]
My temporary fix right now is to create a janky patcher script to run on post-build.

https://github.com/rayriffy/svelte-aio/blob/cc18ac6ec4c7d563aad5f1dc122ecc9829d42499/tools/bun-patcher.js#L6-L11

**Comment by gornostay25** [comment]
https://github.com/gornostay25/svelte-adapter-bun/releases/tag/v0.4.0
